language: node_js
node_js:
  - "5"
  - "6"
  - node
before_script:
  - "npm run lint"
before_install:
  # Travis CI has only shallow clone of the repository. We need to get the 'master' branch
  # so 'conventional-changelog-lint' could compare commits and lint them: marionebl/conventional-changelog-lint#7
  - "git remote set-branches origin master && git fetch && git checkout master && git checkout -"
after_success:
  - "npm run coveralls || true"
  - "npm run semantic-release || true"
env:
  global:
  # travis encrypt NPM_TOKEN="***" GH_TOKEN="***"
  - secure: "BOYu2Vn++pN9LTOVK1YaYLLnol4Cc4fCFBSdVUtMbgAvK+e747oMDUvbTMcRc0Bpypdw4IJJ5d/7ciy5lRpL767v192aD51tSon7ihk8AJC4hZxEHIEpP2fVfToieNwgPfLUTUeen9ZAQqGNmmZ3yPvrOv8+jQtMHoJmmlEqJSyKM6eJnu9p9k9uHQ4QTWKWxJ0IQqCLNxSVvy5BDSB1iy8shEq6BZp5VRRbuir6JJyK+hUmxpwPnkvDnlzRQmmY8cuUd3/Ex0n0ePpELZBmZmGg7j9vK/bl5/P7ReL+xABI/3xOx8Z04COAZHyGDQ5aboAr2n4J4V2vF/N1WD7Lp94N79qIZiMaa3cA1I/lm9mseoSPQTZSL5bRgZAp0/XtKGsEB5bPSyYZf6CdTa1EKRUtlRDYY/5Dj/e8qzts2RFsFi0h2hUNDc2OnujPITjVQS816yNtuZcMpRLAo6sj5gjMaNHnWeEIPAnk52Ncq+b0V03JHL2PSznUBp6CsMv4X5FPMNk7zbc21RabLa5nmeJAkbrWoRntXMakcd+k0YWviitgqXB4eNeQjNhr01l0lV3hUcv6yPzDGyHoqMqnAni9KEtVkF2tzJ3Rw4kk3hFjWZoFsFU8XUTHwHmBA3OXgzCUdgviXJ586embJz9qmAuTJncBMpCSm/Besr5rT7Y="
notifications:
  slack:
    secure: "WSCP8CEYbEJO+FSVwV4CJ6956Ihm5qo3Oxg8E3MG5zLJFGCs4NMe97Gwmqe20yQBTDHN7OL+FGjtWbpXsmpyUtUTOmKR7NzOnmcmu/fNhOHnADS5QLvfOCOq9snXTsiXdfqpkbi+AhpyhQrS+3WHR1JvpNspitv/C6LsiLp2pmN1OfsKR09W889KFKlP9wdYBkeuxmAuJ/I1Y81dW/j/IARW2inBz+MOI1+7N4woWT6KOLKxIcuYQQB8twHiQ4XGS3x8TbRCBFRNUymupUkrS9f+IT27ZGqsn7Xy/hHwVqjzTmJd6Td7NkoEdramM1WqPB9TNza+GQQrIuSmmB1blnyFo1tHWyDmGdvpTdACtBGXY+gtzLzU3VnpzuqLMMX+n1hQvbU/8X7TseTDblcra6Iaf+m6U/+BtnkTKemi3VKENegQTkZ9Jz/h+v94xKGA4b+gkDl76+EpJics1YPeKcfyAD8vQmH2T21OPPQc+NPe0w8FztyKd8D3EdRIeitVb1u4D/6c3haOr2spwr4KF1YdloTwsCeGdQoCMilU4tZM7Kqw7g/SNSD7Af1sdY1nklSLbeZg4Qg4QnuSTZ3nbIyG1GOHYUnabeTewg9sDSrHi7n6DLePsBJWcJEy89pHg61dbHHzqTdGBVY78lGJwFWCY0KekucHcCjULnjFDSU="
