language: node_js
node_js:
  - "6"
  - node
before_script:
  - "npm run lint"
before_install:
  # Travis CI has only shallow clone of the repository. We need to get the 'master' branch
  # so 'conventional-changelog-lint' could compare commits and lint them: marionebl/conventional-changelog-lint#7
  - "git remote set-branches origin master && git fetch && git checkout master && git checkout -"
  - "npm -g install npm@5"
after_success:
#  - "npm run coveralls || true"; @fixme: tempory commenting out, until coveralls flow for JS will be solved
  - "npm run semantic-release || true"
env:
  global:
    # travis encrypt NPM_TOKEN="***" GH_TOKEN="***"
    secure: "yRyDzZCG+kV1HTj4AKyiwuI+NS/fG4fVEn5rPA2gjX+DkahRHdfFcb1UKj308lR51p+kDwp62odlZ3rcUJrLkvpT7fZxdRx8TnAHCa/LjFuveubNaqQuWt+1ygi2t/6nFmQmQs/B1hf6WUnbjP1tMAnvb29+qQ5YFU/j8IlEp/wvmmUVlsynThBGLXu2filjIGmEe8vSR4i3HlCg45dsgTBd7bSuzT9M/BsZjdjGYc4aDohVy/EcvBpnv0EzGHnWF2tkbR03iKo+VW5uC+lQgs9/pUPjxJRrZBTbOpFj62Ohnp2yuyf6VN7C3CYqu0lE2la8FveD/4IQSN+VxrmUSVeGVtA3jWkZKLoxFiYpTg9tOVUOneRJ7kUdt7YjKcmPYl98uLAwf9JG/vNtMS6T+SDDP3hH5Y8QkO6RcBYOB3hBu1igRt/n4yCDyvA6gFrdUSn0dX1s2UdcRR/PpNFJeACscprVfCBsAtuVCRMcSgOB6ZPkQLdHrUUchHbZK4LBaQ7In+IFH9yVPGTSuTyEVMsGuA1Z0bp6yNEkErEUb0EzP2jdPYE6hEFZVn3CZlXnGWvmxnemT2oZFPrtkxmQYRJI0JWtazDzM2/BCXV4Bgys0c7v2I/d/G4QMHMinjZcMkwXJonjeJkYFfxDCUZUDkf1gZarHIT1UJ5taO5T1OQ="
notifications:
  slack:
    secure: "WSCP8CEYbEJO+FSVwV4CJ6956Ihm5qo3Oxg8E3MG5zLJFGCs4NMe97Gwmqe20yQBTDHN7OL+FGjtWbpXsmpyUtUTOmKR7NzOnmcmu/fNhOHnADS5QLvfOCOq9snXTsiXdfqpkbi+AhpyhQrS+3WHR1JvpNspitv/C6LsiLp2pmN1OfsKR09W889KFKlP9wdYBkeuxmAuJ/I1Y81dW/j/IARW2inBz+MOI1+7N4woWT6KOLKxIcuYQQB8twHiQ4XGS3x8TbRCBFRNUymupUkrS9f+IT27ZGqsn7Xy/hHwVqjzTmJd6Td7NkoEdramM1WqPB9TNza+GQQrIuSmmB1blnyFo1tHWyDmGdvpTdACtBGXY+gtzLzU3VnpzuqLMMX+n1hQvbU/8X7TseTDblcra6Iaf+m6U/+BtnkTKemi3VKENegQTkZ9Jz/h+v94xKGA4b+gkDl76+EpJics1YPeKcfyAD8vQmH2T21OPPQc+NPe0w8FztyKd8D3EdRIeitVb1u4D/6c3haOr2spwr4KF1YdloTwsCeGdQoCMilU4tZM7Kqw7g/SNSD7Af1sdY1nklSLbeZg4Qg4QnuSTZ3nbIyG1GOHYUnabeTewg9sDSrHi7n6DLePsBJWcJEy89pHg61dbHHzqTdGBVY78lGJwFWCY0KekucHcCjULnjFDSU="
