language: node_js
node_js:
  - "8"
before_script:
  - "npm run lint"
before_install:
  # Travis CI has only shallow clone of the repository. We need to get the 'master' branch
  # so 'conventional-changelog-lint' could compare commits and lint them: marionebl/conventional-changelog-lint#7
  - "git remote set-branches origin master && git fetch && git checkout master && git checkout -"
  - "npm -g install npm@5"
after_success:
#  - "npm run coveralls || true"; @fixme: tempory commenting out, until coveralls flow for JS will be solved
  - "npm run semantic-release || true"
env:
  global:
    # travis encrypt NPM_TOKEN="***" GH_TOKEN="***"
    secure: WkZz/k/XQH5DZtfRNLe8R1XrurOrThGQ3DydTqvdW679MfmY/PG53q+ENyNjvEIH0OjvtNf22GYBlgCeFXcSYAqqys2MgjgWLPxTF98NGpIIOVCGWuRJxNVlGxhOPMoYj/8/MNPOLpRH+l2/wQdmefh3YC8vvgEDYyyCWxu00DNzz1OTkyCZNK8jBcTWkV48EeiDAhBb72JZVVXpn3uITMrx1jwHCWnXBp0fZPsdaHPYYI9W9hcvWN2cIMHDutMU05HPNduadzaofZTSw3LSFnjGVRaX2aqmMs7lepiym9+lM7/wZuXxEaR82aJAZJ1pIDhMyq/lDtggH1U3RMLOaaVEuJIpksxkne6Dl3sQJAKLegoXdsPDy3IR3sztlB5DFtI/s7xFoIgGpXoNm8jSCJxHF4yaBqKXmWcuqvqBqLEHSAVofaf1DPC7eOvkXdTrbQvWaESBSoIvMJkr0fDTOznCV/MZNWbdT1QUaTo7KIg36vnmetIM5E7xY4qHpJnuKh3MI3PZE3QK/7NPWU/CiqLu/eisqM/W0/3eJ2mMSDQVR2WpO7cgx3E6+VYIfj+UdGTJHxCelW1dOD6nFl+5lub7QnUAWX1sn16Yazt/UYG/xIBa3Z4klruEs9qkeLojg6EhN41g2jwi46Di/xY6c6Rj77j40VuN2yhIzlbJWKA=
notifications:
  slack:
    secure: WSCP8CEYbEJO+FSVwV4CJ6956Ihm5qo3Oxg8E3MG5zLJFGCs4NMe97Gwmqe20yQBTDHN7OL+FGjtWbpXsmpyUtUTOmKR7NzOnmcmu/fNhOHnADS5QLvfOCOq9snXTsiXdfqpkbi+AhpyhQrS+3WHR1JvpNspitv/C6LsiLp2pmN1OfsKR09W889KFKlP9wdYBkeuxmAuJ/I1Y81dW/j/IARW2inBz+MOI1+7N4woWT6KOLKxIcuYQQB8twHiQ4XGS3x8TbRCBFRNUymupUkrS9f+IT27ZGqsn7Xy/hHwVqjzTmJd6Td7NkoEdramM1WqPB9TNza+GQQrIuSmmB1blnyFo1tHWyDmGdvpTdACtBGXY+gtzLzU3VnpzuqLMMX+n1hQvbU/8X7TseTDblcra6Iaf+m6U/+BtnkTKemi3VKENegQTkZ9Jz/h+v94xKGA4b+gkDl76+EpJics1YPeKcfyAD8vQmH2T21OPPQc+NPe0w8FztyKd8D3EdRIeitVb1u4D/6c3haOr2spwr4KF1YdloTwsCeGdQoCMilU4tZM7Kqw7g/SNSD7Af1sdY1nklSLbeZg4Qg4QnuSTZ3nbIyG1GOHYUnabeTewg9sDSrHi7n6DLePsBJWcJEy89pHg61dbHHzqTdGBVY78lGJwFWCY0KekucHcCjULnjFDSU=
